# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Resume
    url: resume/
    weight: 20
  - name: Portofolio
    url: portofolio/
    weight: 30
  # - name: Knowledge Garden
  #   url: https://ifkarsyah-garden.pages.dev/
  #   weight: 40
  - name: Choosing Tool
    identifier: choosing-tool
    url: /choosing-tool
    weight: 40
  - name: Book resume
    url: /reading
    weight: 50
  - name: Tutorial
    identifier: tutorial
    url: /tutorial
    weight: 60
  - name: Apache Flink
    url: /tutorial-flink
    parent: tutorial
  - name: Apache Kafka
    url: /tutorial-kafka
    parent: tutorial
  - name: PostgreSQL
    url: /tutorial-postgresql
    parent: tutorial
